name: PMD Analysis

on: [push, pull_request]

jobs:
  pmd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run PMD
      uses: pmd/pmd-action@v3
      with:
        target_directory: 'src'
        report_format: 'html'
        rule_set: 'ruleset.xml'
